name: Drift Detection

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch: 

jobs:
  nightly-drift:
    runs-on: ubuntu-latest
    
    concurrency:                           # avoid overlaps
      group: drift-${{ github.ref }}
      cancel-in-progress: true

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Deps
        run: pip install evidently pandas boto3

      - name: Run Drift Report
        run: python monitoring/run_drift.py

      - name: Commit DRIFT.flag (if any)
        run: |
          if test -f DRIFT.flag; then
            git config user.name github-actions-bot
            git config user.email github-actions-bot@users.noreply.github.com
            git add DRIFT.flag
            git commit -m "DATA_UPDATE $(date -u +%F)" || true
            git push
          fi
