name: Detect Drift and Retrain

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch: 

jobs:
  detect-drift:
    runs-on: ubuntu-latest
    
    concurrency:                           # avoid overlaps
      group: drift-${{ github.ref }}
      cancel-in-progress: true

    permissions:
      id-token: write
      contents: write

    outputs:
      drift: ${{ steps.drift-flag.outputs.drift }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - run: echo ${{ secrets.OIDC_ROLE }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Dependencies
        run: pip install evidently pandas boto3

      - name: Run Drift Report
        id: drift-flag
        run: python -m scripts.detect_drift

      - name: Update files
        if: steps.drift-flag.outputs.drift == 'true'
        run: echo "True"
        
      - name: Update files False
        if: steps.drift-flag.outputs.drift == 'false'
        run: echo "False"
          
  retrain:
    needs: detect-drift
    if: needs.detect-drift.outputs.drift == 'true'
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     role-to-assume: ${{ secrets.OIDC_ROLE }}
      #     aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Dependencies
        run: |
          pip install --no-cache-dir torch --index-url https://download.pytorch.org/whl/cpu
          pip install --no-cache-dir -r requirements.txt

      - name: Retrain
        run: python -m src.training.train
      
      - name: Push Artifacts
        run: |
          git config user.name github-actions-bot
          git config user.email github-actions-bot@users.noreply.github.com
          git add artifacts
          git commit -m "Auto-retrain: $(date -u +%F)" || echo "No changes"
          git push

