name: Detect Drift and Retrain

on:
  # schedule:
  #   - cron: '0 4 * * *'
  workflow_dispatch: 

jobs:
  detect-drift:
    runs-on: ubuntu-latest

    env:
      S3_BUCKET: fraud-detection-dvc-store
      FOLDER_NAME: incoming
    
    concurrency:                           # avoid overlaps
      group: drift-${{ github.ref }}
      cancel-in-progress: true

    permissions:
      id-token: write
      contents: write

    outputs:
      drift: ${{ steps.drift-flag.outputs.drift }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Dependencies
        run: pip install evidently pandas boto3 dvc[s3]

      - name: Pull Data & Artifacts
        run: dvc pull -q

      - name: Sync Files From S3
        run: |
          mkdir -p data/incoming
          aws s3 sync s3://$S3_BUCKET/$FOLDER_NAME data/$FOLDER_NAME --delete --exact-timestamps
          echo "NEWFILES=$(ls -1 data/$FOLDER_NAME | wc -l)" >> $GITHUB_ENV

      - name: Run Drift Report
        if: env.NEWFILES != '0'
        id: drift-flag
        run: |
          python -m scripts.merge_incoming_files
          python -m scripts.detect_drift

      - name: Replace Baseline
        if: steps.drift-flag.outputs.drift == 'true'
        run: |
          python -m scripts.replace_baseline
        
      - name: Modify Baseline
        if: steps.drift-flag.outputs.drift == 'false'
        run: |
          python -m scripts.update_baseline
          
      - name: Update DVC and S3
        if: env.NEWFILES != '0'
        run: |
          aws s3 sync data/$FOLDER_NAME s3://$S3_BUCKET/$FOLDER_NAME --delete --exact-timestamps
          dvc add data/baseline.csv
          dvc push

      - name: Push Data
        if: env.NEWFILES != '0'
        run: |
          git config user.name github-actions-bot
          git config user.email github-actions-bot@users.noreply.github.com
          git add data
          git commit -m "Auto-update: $(date -u +%F)" || echo "No changes"
          git push
          
  retrain:
    needs: detect-drift
    if: needs.detect-drift.outputs.drift == 'true'
    
    runs-on: ubuntu-latest

    env:
      CLEARML_API_ACCESS_KEY: ${{ secrets.CLEARML_API_ACCESS_KEY }}
      CLEARML_API_SECRET_KEY: ${{ secrets.CLEARML_API_SECRET_KEY }}
      CLEARML_API_HOST: ${{ secrets.CLEARML_API_HOST }}

    permissions:
      contents: write      # <- allow git push
      id-token: write      # (keep this if you still assume the AWS role)

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Dependencies
        run: |
          pip install --no-cache-dir torch --index-url https://download.pytorch.org/whl/cpu
          pip install --no-cache-dir -r requirements.txt
          pip install --no-cache-dir dvc[s3]

      - name: Pull Data & Artifacts
        run: dvc pull -q

      - name: Retrain
        run: python -m src.training.train

      - name: Update DVC and S3
        run: |
          dvc add artifacts
          dvc push
          
      - name: Push Artifacts
        run: |
          git config user.name github-actions-bot
          git config user.email github-actions-bot@users.noreply.github.com
          git add artifacts.dvc
          git commit -m "Auto-retrain: $(date -u +%F)" || echo "No changes"
          git push

  deploy:
    needs: retrain
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Pull Data & Artifacts
        run: dvc pull artifacts -q

      - name: Build Docker Image
        run: |
          docker build -t fraud-detection-api .
          docker tag fraud-detection-api:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/fraud-detection-api:latest

      - name: Push Docker Image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/fraud-detection-api:latest

      - name: Update ECS Service
        run: |
          aws ecs update-service \
            --cluster fraud-detection-cluster \
            --service fraud-detection-service \
            --force-new-deployment \
            --region ${{ secrets.AWS_REGION }}
