name: Detect Drift and Retrain

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch: 

jobs:
  detect-drift:
    runs-on: ubuntu-latest
    
    concurrency:                           # avoid overlaps
      group: drift-${{ github.ref }}
      cancel-in-progress: true

    permissions:
      id-token: write
      contents: write

    outputs:
      drift: ${{ steps.drift-flag.outputs.drift }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Deps
        run: pip install evidently pandas boto3

      - name: Run Drift Report
        run: python monitoring/run_drift.py

      - name: Detect Drift
        id: drift-flag
        run: |
          if test -f DRIFT.flag; then
            echo "drift=true" >> "$GITHUB_OUTPUT"
          fi
          
  retrain:
    needs: detect-drift
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

